### ISSUE TITLE
[IntelliJ] No tests found for given includes

### ISSUE THREAD

**Issue by DolphaGo** [DolphaGo/Issues#42]
Settings > Build,Execution,Deployment > Build Tools > Gradle > Build and Run

![image](https://user-images.githubusercontent.com/37108728/128328660-89a86ff8-496c-44f8-85e4-e2e504a7313e.png)

**Comment by karnick** [comment]
@DolphaGo the suggested workaround doesn't help. We still are getting 

```
Execution failed for task ':XXXX:test'.
> No tests found for given includes: [com.XXXX.ProcessorTest.myTEST](filter.includeTestsMatching)
```
